apiVersion: v1
kind: Service
metadata:
  labels: {{- include "cobbler-tftp.labels" . | nindent 4 }}
  name: {{ include "cobbler-tftp.fullname" . }}
spec:
  ports:
    - name: tftp
      port: {{ .Values.service.port }}
      protocol: UDP
      targetPort: tftp
  selector: {{- include "cobbler-tftp.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
