apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  NetboxToken: {{ .Values.appSecrets.netboxToken | quote }}
  OrthosKey: {{ .Values.appSecrets.orthosKey | quote }}
  OIDCsecret: {{ .Values.appSecrets.oidcSecret | quote }}
