apiVersion: v2
name: cobbler-web
description: A Helm Chart to host the Cobbler Web UI.
type: application
version: 0.1.2
appVersion: "v0.0.1-rc4"
icon: https://avatars.githubusercontent.com/u/1179083?s=200&v=4
maintainers:
  - name: SchoolGuy
    email: matrixfueller@gmail.com
    url: https://github.com/SchoolGuy
home: https://github.com/cobbler/charts
sources:
  - https://github.com/cobbler/charts
keywords:
  - Cobbler
