{{- if .Values.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: orthos2-env
  labels:
    {{- include "orthos2.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
