{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: orthos2
  labels:
    {{- include "orthos2.labels" . | nindent 4 }}
type: Opaque
stringData:
  NetboxToken: {{ .Values.secrets.netboxToken | quote }}
  OIDCsecret: {{ .Values.secrets.oidcSecret | quote }}
  OrthosKey: {{ .Values.secrets.orthosKey | quote }}
  OrthosPostgresPassword: {{ .Values.secrets.postgresPassword | quote }}
{{- end }}
